### ISSUE TITLE
执行或编译异常

### ISSUE THREAD

**Issue by CSecurityZhongYuan** [aliyun/coolbpf#15]
python pip安装完之后运行hello报错
surftrace.surfException.DbException: db set return setup obj report: [Errno 2] No such file or directory: '.output/lbc.bpf.o'.

golcc中hello在make时也会报这个错，是什么依赖没安装吗

**Comment by CSecurityZhongYuan** [comment]
具体错误如下
#bpf/hello.bpf.c
cp /home/tower/aiwencode/coolbpf/lcc/golcc/rexample/hello/bpf/hello.bpf.c /home/tower/aiwencode/coolbpf/lcc/golcc/rexample/hello
coolbpf -f hello.bpf.c -o
compile failed.
ln -sf ../../hive/header/x86_64/vmlinux-5.15.0-53-generic.h bpf/vmlinux.h
python tool/replaceHead.py bpf/lbc.org.h bpf/vmlinux.h bpf/lbc.h
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I.output -I/home/lbc/include -Iinclude -Ibpf -Ilibbpf/include/uapi -I /usr/local/include -I /usr/local/lib/clang/12.0.1/include -I /usr/include  -c bpf/lbc.bpf.c -o .output/lbc.bpf.o
bpf/lbc.bpf.c:7:53: error: incomplete definition of type 'struct pt_regs'
        struct task_struct *parent = (struct task_struct *)PT_REGS_PARM1(ctx);
                                                           ^~~~~~~~~~~~~~~~~~
/home/lbc/include/bpf/bpf_tracing.h:104:30: note: expanded from macro 'PT_REGS_PARM1'
#define PT_REGS_PARM1(x) ((x)->rdi)
                          ~~~^
/home/lbc/include/bpf/bpf_helper_defs.h:20:8: note: forward declaration of 'struct pt_regs'
struct pt_regs;
       ^
bpf/lbc.bpf.c:9:49: error: incomplete definition of type 'struct task_struct'
        bpf_printk("hello golcc, parent:%d\n", _(parent->tgid));
                                                 ~~~~~~^
/home/lbc/include/bpf/bpf_helpers.h:22:7: note: expanded from macro 'bpf_printk'
                         ##__VA_ARGS__);                \
                           ^~~~~~~~~~~
bpf/lbc.h:132:23: note: expanded from macro '_'
#define _(P) ({typeof(P) val = 0; bpf_probe_read((void*)&val, sizeof(val), (const void*)&P); val;})
                      ^
/home/lbc/include/bpf/bpf_helper_defs.h:30:8: note: forward declaration of 'struct task_struct'
struct task_struct;
       ^
bpf/lbc.bpf.c:9:49: error: incomplete definition of type 'struct task_struct'
        bpf_printk("hello golcc, parent:%d\n", _(parent->tgid));
                                                 ~~~~~~^
/home/lbc/include/bpf/bpf_helpers.h:22:7: note: expanded from macro 'bpf_printk'
                         ##__VA_ARGS__);                \
                           ^~~~~~~~~~~
bpf/lbc.h:132:90: note: expanded from macro '_'
#define _(P) ({typeof(P) val = 0; bpf_probe_read((void*)&val, sizeof(val), (const void*)&P); val;})
                                                                                         ^
/home/lbc/include/bpf/bpf_helper_defs.h:30:8: note: forward declaration of 'struct task_struct'
struct task_struct;
       ^
bpf/lbc.bpf.c:9:41: error: argument type 'void' is incomplete
        bpf_printk("hello golcc, parent:%d\n", _(parent->tgid));
                                               ^
4 errors generated.
make: *** [.output/lbc.bpf.o] Error 1


Traceback (most recent call last):
  File "/home/tower/.local/bin/coolbpf", line 8, in <module>
    sys.exit(main())
  File "/home/tower/.local/lib/python3.8/site-packages/coolbpf/coolbpf.py", line 44, in main
    ClbcLoad(args.file, arch=args.arch,
  File "/home/tower/.local/lib/python3.8/site-packages/pylcc/lbcBase.py", line 79, in __init__
    self._compileObj(bpf, bpf_str, ver, arch)
  File "/home/tower/.local/lib/python3.8/site-packages/pylcc/lbcBase.py", line 233, in _compileObj
    dRecv = cli.getObj(s, self._env)
  File "/home/tower/.local/lib/python3.8/site-packages/surftrace/lbcClient.py", line 153, in getObj
    return self._post(dSend, tmo=30)
  File "/home/tower/.local/lib/python3.8/site-packages/surftrace/lbcClient.py", line 87, in _post
    raise DbException('db set return %s' % ret["log"])
surftrace.surfException.DbException: db set return setup obj report: [Errno 2] No such file or directory: '.output/lbc.bpf.o'.
make: *** [Makefile:19: hello.bpf.o] Error 1

**Comment by liaozhaoyan** [comment]
可以提供下你的代码么？

**Comment by CSecurityZhongYuan** [comment]
是项目提供的测试样例
coolbpf/lcc/golcc/rexample/hello    这个目录
执行了make，报错

**Comment by liaozhaoyan** [comment]
> 

sorry,我稍后同步下代码。

**Comment by liaozhaoyan** [comment]
已经更新代码，你可以 pip install -U coolbpf; git pull 后再看一下呢？

**Comment by CSecurityZhongYuan** [comment]
执行上面代码之后依然报错

coolbpf/lcc/golcc/rexample/hello$ make
cp /home/tower/aiwencode/coolbpf/lcc/golcc/rexample/hello/bpf/hello.bpf.c /home/tower/aiwencode/coolbpf/lcc/golcc/rexample/hello
coolbpf -f hello.bpf.c -o
compile failed.
ln -sf ../../hive/header/x86_64/vmlinux-5.15.0-53-generic.h bpf/vmlinux.h
python tool/replaceHead.py bpf/lbc.org.h bpf/vmlinux.h bpf/lbc.h
clang -g -O2 -target bpf -D__TARGET_ARCH_x86 -I.output -I/home/lbc/include -Iinclude -Ibpf -Ilibbpf/include/uapi -I /usr/local/include -I /usr/local/lib/clang/12.0.1/include -I /usr/include  -c bpf/lbc.bpf.c -o .output/lbc.bpf.o
bpf/lbc.bpf.c:7:53: error: incomplete definition of type 'struct pt_regs'
        struct task_struct *parent = (struct task_struct *)PT_REGS_PARM1(ctx);
                                                           ^~~~~~~~~~~~~~~~~~
/home/lbc/include/bpf/bpf_tracing.h:104:30: note: expanded from macro 'PT_REGS_PARM1'
#define PT_REGS_PARM1(x) ((x)->rdi)
                          ~~~^
/home/lbc/include/bpf/bpf_helper_defs.h:20:8: note: forward declaration of 'struct pt_regs'
struct pt_regs;
       ^
1 error generated.
make: *** [.output/lbc.bpf.o] Error 1


Traceback (most recent call last):
  File "/home/tower/.local/bin/coolbpf", line 8, in <module>
    sys.exit(main())
  File "/home/tower/.local/lib/python3.8/site-packages/coolbpf/coolbpf.py", line 44, in main
    ClbcLoad(args.file, arch=args.arch,
  File "/home/tower/.local/lib/python3.8/site-packages/pylcc/lbcBase.py", line 79, in __init__
    self._compileObj(bpf, bpf_str, ver, arch)
  File "/home/tower/.local/lib/python3.8/site-packages/pylcc/lbcBase.py", line 233, in _compileObj
    dRecv = cli.getObj(s, self._env)
  File "/home/tower/.local/lib/python3.8/site-packages/surftrace/lbcClient.py", line 153, in getObj
    return self._post(dSend, tmo=30)
  File "/home/tower/.local/lib/python3.8/site-packages/surftrace/lbcClient.py", line 87, in _post
    raise DbException('db set return %s' % ret["log"])
surftrace.surfException.DbException: db set return setup obj report: [Errno 2] No such file or directory: '.output/lbc.bpf.o'.
make: *** [Makefile:17: hello.bpf.o] Error 1

**Comment by liaozhaoyan** [comment]
方便提供下你的os 信息么？ uname -r

**Comment by liaozhaoyan** [comment]
ubuntu 现在支持还不是很好，当前支持较好的是centos/alinux/anolis
